### ISSUE TITLE
Recursive values result in a table overflow when interacting with certain components

### ISSUE THREAD

**Issue by ultoof** [VirtualButFake/vfx-editor#3]
Im having consistent encounters with an issue which freezes roblox studio or crashes it rarely, whenever i try to add a new texture to the texture library roblox freezes when i insert the id, it usually unfreezes after around 10-15 seconds. When i try to change the flipbook layout the menu does not open and studio yust does not respond and crashes after a few seconds.

Im on version v1.0.8, output below

Random Freeze when clicking ui:
![image_2024-08-11_191416725](https://github.com/user-attachments/assets/bd6e7ed9-1650-4192-9061-058304ee405d)

Asset id freeze:
![image_2024-08-11_191533934](https://github.com/user-attachments/assets/3138daad-a99f-4629-9fa7-97121ce6e113)

Roblox studio is updated and my drivers are too, im using an AMD Raedon graphics card if that may be the issue for some reason, i think this plugin would be great for the roblox vfx scene if you fixed these issues. Good work!

**Comment by ultoof** [comment]
after reading the wiki 5 mins after posting this i found out you need to enable http requests for this plugin to work lol, sorry for the report. I cant seem to paste asset ids tho cus studio yust crashes

**Comment by ultoof** [comment]
ctrl v seems to be the cause of the crash

**Comment by tijnepema** [comment]
Do you have any error logs?
